---
title: "Exploring the efficacy of psychological treatments for depression: a multiverse meta-analysis protocol"
---

# Abstract

ABSTRACT
Introduction In the past four decades, over 700
randomised controlled trials (RCTs) and 80 meta-analyses
have examined the efficacy of psychological treatments
for depression. Overwhelming evidence suggests that all
types of psychological treatments are effective. Yet, many
aspects are still unexplored. Meta-analysts could perform
hundreds of potential meta-analyses with the current
literature, and a comprehensive bird’s-eye view of all
published studies is missing. This protocol outlines how a
multiverse meta-analysis can evaluate the entire body of
the literature on psychological treatments of depression in
a single analysis. Thereby, gaps of evidence and areas of
robustness are highlighted.
Methods and analysis We will conduct systematic
literature searches in bibliographical databases (PubMed,
Embase, PsycINFO and Cochrane Register of Controlled
Trials) up until 1 January 2021. We will include all
RCTs comparing a psychological treatment with a
control condition. We will include studies published in
English, German, Spanish or Dutch, and exclude trials
on maintenance and relapse prevention as well as
dissertations. Two independent researchers will check all
records. All self-reported and clinician-rated instruments
measuring depression are included. We will extract
information on recruitment settings, target groups, age
groups, comorbidity, intervention formats, psychotherapy
types, number of sessions, control conditions and country.
Two independent researchers will assess risk of bias using
the Cochrane Risk of Bias assessment tool. As part of the
multiverse meta-analysis, unweighted, fixed effect and
random effects models will be calculated.
Ethics and dissemination As we will not collect any
primary data, an ethical approval of this protocol is not
required. We will publish the results in a peer-review
journal and present them at international conferences. We
will follow open science practices and provide our code
and data.

# [Link to full texz](thttps://bmjopen.bmj.com/content/bmjopen/12/1/e050197.full.pdf)
