---
title: "Publications"
editor: visual
---

## \### **2024**

-   Cuijpers, P., Harrer, M., Miguel, C., Ciharova, M., Basic, D., Cristea, I. A., de Ponti, N., Driessen, E., Hamblen, J., Larsen, S. E., Matbouriahi, M., Papola, D., Pauley, D., **Plessen, C. Y.**, Pfund, R. A., Setkowski, K., Schnurr, P. P., van Ballegooijen, W., Wang, Y., Riper, H., van Straten, A., Sijbrandij, M., Furukawa, T. A., & Karyotaki, E. (2024). Cognitive behavior therapy for mental disorders in adults: A unified series of meta-analyses across 375 randomized trials. *Under Review: JAMA Psychiatry*.

-   Harrer, M., Miguel, C., van Ballegooijen, W., Ciharova, M., **Plessen, C. Y.**, Kuper, P., Sprenger, A. A., Buntrock, C., Papola, D., Cristea, I. A., de Ponti, N., Basic, D., Pauley, D., Driessen, E., Quero, S., Grimaldos, J., Fernández Buendía, S., Botella, C., Hamblen, J. L., Schnurr, P. P., Larsen, S. E., Pfund, R. A., Motrico, E., Goméz-Goméz, I., Setkowski, K., Matbouriahi, M., Wang, Y., Rawee, J., Riper, H., van Straten, A., Sijbrandij, M., Leucht, S., Furukawa, T. A., Karyotaki, E., & Cuijpers, P. (2024). Supersizing meta-analysis of psychological interventions: Features and findings of the “Metapsy” meta-analytic research domain. *Under Review*.

-   **Plessen, C. Y.** (2024). Research synthesis of psychological interventions for mental health. *Doctoral dissertation, Vrije Universiteit Amsterdam.* <https://research.vu.nl/en/publications/research-synthesis-of-psychological-interventions-for-mental-heal>.

-   Miguel, C., Harrer, M., Karyotaki, E., **Plessen, C. Y.**, Ciharova, M., Furukawa, T. A., Cristea, I. A., & Cuijpers, P. (2024). Self-reports vs clinician ratings of efficacies of psychotherapies for depression: A meta-analysis of randomized trials. *Under Review*.

-   Scholz, C., Schmigalle, P., **Plessen, C. Y.**, Liegl, G., Vajkoczy, P., Prasser, F., Rose, M., & Obbarius, A. (2024). The effect of self-management techniques on relevant outcomes in chronic low back pain: A systematic review and meta-analysis. *European Journal of Pain, 28*(4), 532–550. <https://doi.org/10.1002/ejp.2221>.

-   Cuijpers, P., Miguel, C., Ciharova, M., Harrer, M., Basic, D., Cristea, I. A., de Ponti, N., Driessen, E., Hamblen, J., Larsen, S. E., Matbouriahi, M., Papola, D., Pauley, D., **Plessen, C. Y.**, Pfund, R. A., Setkowski, K., Schnurr, P. P., van Ballegooijen, W., Wang, Y., Riper, H., & Karyotaki, E. (2024). Absolute and relative outcomes of psychotherapies for eight mental disorders: A systematic review and meta-analysis. *World Psychiatry, 23*(2), 267–275. <https://doi.org/10.1002/wps.21203>.

-   **Plessen, C. Y.**, Panagiotopoulou, O. M., Tong, L., Cuijpers, P., & Karyotaki, E. (2024). Digital mental health interventions for the treatment of depression: A multiverse meta-analysis. *Journal of Affective Disorders, 369*, 1031–1044. <https://doi.org/10.1016/j.jad.2024.10.018>.

-   Cuijpers, P., Miguel, C., Harrer, M., **Plessen, C. Y.**, Ciharova, M., Papola, D., Ebert, D., & Karyotaki, E. (2024). Randomised trials on psychotherapy for depression: Methods of a ‘meta-analytic research domain.’ *Under Review: Systematic Reviews*.

-   **Plessen, C. Y.**, Hartmann, C., Heng, M., Pesantez, R., Fischer, F., & Rose, M. (2024). Differential item functioning between English, German, and Spanish PROMIS® physical function ceiling items. *In Press: Quality of Life Review.*

-   **Plessen, C. Y.**, Liegl, G., Hartmann, C., Heng, M., Joeris, A., Kaat, A. J., Schalet, B. D., Fischer, F., Rose, M., & AOBERT Consortium (2024). How are age, gender, and country differences associated with PROMIS physical function, upper extremity, and pain interference scores? *Clinical Orthopaedics and Related Research, 482*(2), 244–256. <https://doi.org/10.1097/CORR.0000000000002798>.

<br>

### **2023**

---
-   Cuijpers, P., Miguel, C., Harrer, M., **Plessen, C. Y.**, et al. (2023). Psychological treatment of depression: A systematic overview of a ‘meta-analytic research domain.’ *Journal of Affective Disorders, 335*, 141–151. <https://doi.org/10.1016/j.jad.2023.05.011>.

-   Harrison, C. J., **Plessen, C. Y.**, Liegl, G., Rodrigues, J. N., Sabah, S. A., Beard, D. J., & Fischer, F. (2023). Overcoming floor and ceiling effects in knee arthroplasty outcome measurement. *Bone & Joint Research, 12*(10), 624–635. <https://doi.org/10.1302/2046-3758.1210.BJR-2022-0457.R1>.

-   Conrad, J. H., **Plessen, C. Y.**, Liegl, G., Rodrigues, J. N., Sabah, S. A., Beard, D. J., & Fischer, F. (2023). Item response theory may account for unequal item weighting and individual-level measurement error in trials that use PROMs: A psychometric sensitivity analysis of the TOPKAT trial. *Journal of Clinical Epidemiology, 158*, 62–69. <https://doi.org/10.1016/j.jclinepi.2023.03.013>.

-   **Plessen, C. Y.**, Karyotaki, E., Miguel, C., Ciharova, M., & Cuijpers, P. (2023). Exploring the efficacy of psychotherapies for depression: A multiverse meta-analysis. *BMJ Mental Health, 26*(1), e300626. <https://doi.org/10.1136/bmjment-2022-300626>.

-   Cuijpers, P., Miguel, C., Harrer, M., **Plessen, C. Y.**, et al. (2023). Cognitive behavior therapy vs. control conditions, other psychotherapies, pharmacotherapies, and combined treatment for depression: A comprehensive meta-analysis including 409 trials with 52,702 patients. *World Psychiatry, 22*(1), 105–115. <https://doi.org/10.1002/wps.21069>.

-   Cuijpers, P., Miguel, C., Harrer, M., **Plessen, C. Y.**, Ciharova, M., Papola, D., Ebert, D., & Karyotaki, E. (2023). Psychological treatment of depression with other comorbid mental disorders: Systematic review and meta-analysis. *Cognitive Behaviour Therapy.* <https://doi.org/10.1080/16506073.2023.2166578>.

<br>

### **2022 and Before**
---

-   **Plessen, C. Y.**, Karyotaki, E., & Cuijpers, P. (2022). Exploring the efficacy of psychological treatments for depression: A multiverse meta-analysis protocol. *BMJ Open, 12*(1), e050197. <https://doi.org/10.1136/bmjopen-2021-050197>.

-   **Plessen, C. Y.**, Gyimesi, M. L., Kern, B. M. J., Fritz, T., Catalán Lorca, M. V., Voracek, M., & Tran, U. S. (2020). Associations between academic dishonesty and personality: A pre-registered multilevel meta-analysis. *PsyArXiv*. <https://psyarxiv.com/pav2f/>.

-   **Plessen, C. Y.**, Lammer, A., Tran, U. S., & Voracek, M. (2020). Twin-singleton differences in intelligence: An updated and pre-registered meta-analysis. *Manuscript in preparation*.

-   **Plessen, C. Y.**, Franken, F., Kathofer, M., Kotlyar, E., Maierwieser, R. J., Mayer, A., Rattner, K., Schmid, R. R., Sobisch, M., Ster, C., Wolfmayer, C., & Tran, U. S. (2020). Humor-styles and personality traits: An updated meta-analysis. *Personality and Individual Differences, 154*, 109676. <https://doi.org/10.1016/j.paid.2019.109676>.

-   Kossmeier, K., Vilsmeier, J., Dittrich, R., Fritz, T., Kolmanz, C., **Plessen, C. Y.**, Slowik, A., Tran, U. S., & Voracek, M. (2019). Long-term trends (1980–2017) in the N-pact factor: Comparative meta-research of journals in personality psychology and individual differences research. *Zeitschrift für Psychologie, 227*, 293–302. <https://doi.org/10.1027/2151-2604/a000384>.

-   **Plessen, C. Y.** (2017). Who smokes and drinks? Formal education and time perspective as predictors of differences in alcohol and tobacco intake. *Unpublished bachelor’s thesis*. University of Vienna.

-   **Plessen, C. Y.**, Boeckle, M., Liegl, G., Leitner, A., Schneider, A., Preining, B., & Pieh, C. (2016). \[Supply and demand analysis for psychotherapy in Austria\] Bedarfsanalyse für ambulante Psychotherapie in Österreich. *Psychologische Medizin, 3*, 4–9.

-   Liegl, G., **Plessen, C. Y.**, Leitner, A., Boeckle, M., & Pieh, C. (2015). Guided self-help interventions for irritable bowel syndrome: A systematic review and meta-analysis. *European Journal of Gastroenterology & Hepatology, 27*, 1209–1221. <https://doi.org/10.1097/MEG.0000000000000428>.
